# Generated by Django 4.2 on 2025-06-28 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('slot', models.TimeField()),
                ('duration_min', models.IntegerField()),
                ('phone_number', models.BigIntegerField()),
                ('is_paid', models.BooleanField(default=False)),
                ('question', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BeautyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('percent', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.BigIntegerField()),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Beauty City', max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('beauty_services', models.DateTimeField()),
                ('image', models.ImageField(upload_to='')),
                ('work_start_at', models.TimeField()),
                ('work_end_time', models.TimeField()),
                ('services', models.ManyToManyField(related_name='salons', to='Salons.beautyservice')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(max_length=100)),
                ('spec', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Salons.salon')),
                ('skills', models.ManyToManyField(related_name='specialists', to='Salons.beautyservice')),
            ],
        ),
        migrations.CreateModel(
            name='ClientReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.BigIntegerField()),
                ('review', models.TextField()),
                ('rating', models.CharField(choices=[('1', '★☆☆☆☆'), ('2', '★★☆☆☆'), ('3', '★★★☆☆'), ('4', '★★★★☆'), ('5', '★★★★★')], max_length=1)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Salons.appointment')),
            ],
        ),
        migrations.AddField(
            model_name='beautyservice',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Salons.servicetype'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='Promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Salons.promo'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Salons.beautyservice'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Salons.specialist'),
        ),
    ]
