# Generated by Django 4.2 on 2025-06-28 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Salons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salon',
            name='beauty_services',
        ),
    ]
