# Generated by Django 4.2 on 2025-06-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salons', '0002_remove_salon_beauty_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='image',
            field=models.ImageField(upload_to='salon_images/'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='photo',
            field=models.ImageField(upload_to='specialist_images/'),
        ),
    ]
