# Generated by Django 4.2 on 2025-06-28 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Salons', '0003_alter_salon_image_alter_specialist_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beautyservice',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='Salons.servicetype'),
        ),
    ]
