# Generated by Django 4.2 on 2025-06-28 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Salons', '0004_alter_beautyservice_service_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salon',
            name='services',
        ),
    ]
