# Generated by Django 4.2 on 2025-06-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salons', '0005_remove_salon_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='name',
            field=models.CharField(default='Имя', max_length=100),
            preserve_default=False,
        ),
    ]
