# Generated by Django 4.2 on 2025-06-29 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Salons', '0006_specialist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='Salons.specialist'),
        ),
    ]
