# Generated by Django 4.2 on 2025-06-29 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salons', '0008_alter_clientreview_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
