# Generated by Django 4.2 on 2025-06-30 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Salons', '0009_alter_review_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientreview',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_rating', to='Salons.appointment'),
        ),
    ]
