# Generated by Django 4.2 on 2025-07-01 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Salons', '0013_review_visit_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='visit_date',
        ),
    ]
