# Generated by Django 4.2 on 2025-07-02 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Salons', '0014_remove_review_visit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialists', to='Salons.salon'),
        ),
    ]
