# Generated by Django 4.2 on 2025-07-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salons', '0015_alter_specialist_salon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='question',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
