# Generated by Django 4.2 on 2025-07-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salons', '0016_alter_appointment_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='duration_min',
            field=models.IntegerField(default=60),
        ),
    ]
